spring.application.name=algorizzmus-auth-service
spring.datasource.url=jdbc:postgresql://localhost:5433/algorizzmus-auth-service-db
spring.datasource.username=algorizzmus
spring.datasource.password=${DATASOURCE_PASSWORD}
jwt.secret=8a12ccbecffd2af1ce2d3b5247d0dbb87a17d30aed3e3df33326639c8258cf74de364307baa83c501aa09f6aba325ffa