spring.application.name=algorizzmus-auth-service
spring.datasource.url=jdbc:postgresql://localhost:5432/algorizzmus-auth-service-db
spring.datasource.username=algorizzmus
spring.datasource.password=PtWBaWJGGbHiSrC
