spring.application.name=algorizzmus-auth-service
spring.datasource.url=jdbc:postgresql://localhost:5433/algorizzmus-auth-service-db
spring.datasource.username=algorizzmus
spring.datasource.password=PtWBaWJGGbHiSrC
jwt.secret=${JWT_SECRET:defaultSecretKeyForDevelopmentEnvironmentOnly}
# JavaMailSender Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
