CREATE TABLE email_verification_tokens
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id         BIGINT                                  NOT NULL,
    token           VARCHAR(255)                            NOT NULL,
    expiration_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    is_verified     BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_email_verification_tokens PRIMARY KEY (id)
);

ALTER TABLE users
    ADD email VARCHAR(255);

ALTER TABLE users
    ADD is_email_verified BOOLEAN;

ALTER TABLE users
    ADD name VARCHAR(255);

ALTER TABLE users
    ADD surname VARCHAR(255);

ALTER TABLE email_verification_tokens
    ADD CONSTRAINT uc_email_verification_tokens_token UNIQUE (token);

ALTER TABLE email_verification_tokens
    ADD CONSTRAINT uc_email_verification_tokens_user UNIQUE (user_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE email_verification_tokens
    ADD CONSTRAINT FK_EMAIL_VERIFICATION_TOKENS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);