ALTER TABLE email_verification_tokens
DROP
CONSTRAINT fk_email_verification_tokens_on_user;

CREATE TABLE verification_codes
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id         BIGINT                                  NOT NULL,
    code            VARCHAR(255)                            NOT NULL,
    expiration_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_verification_codes PRIMARY KEY (id)
);

ALTER TABLE verification_codes
    ADD CONSTRAINT uc_verification_codes_code UNIQUE (code);

ALTER TABLE verification_codes
    ADD CONSTRAINT uc_verification_codes_user UNIQUE (user_id);

ALTER TABLE verification_codes
    ADD CONSTRAINT FK_VERIFICATION_CODES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

DROP TABLE email_verification_tokens CASCADE;